language: objective-c
os: osx
osx_image: xcode10.2

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - PROJECT=ImageTransition.xcodeproj
    - CONFIG=Release
    - ACTION="build-for-testing test-without-building"

matrix:
  include:
    - env: JOB=xcode SCHEME=ImageTransition SDK=iphonesimulator

branches:
  only:
    - master

cache:
  directories:
    - Carthage

script:
  - set -o pipefail
  - xcodebuild $ACTION -project $PROJECT -scheme $SCHEME -sdk $SDK -destination 'name=iPhone 8,OS=11.4' -configuration $CONFIG ENABLE_TESTABILITY=YES | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash)
